default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV["DATABASE_PASSWORD_LOCAL"] %>
  username: <%= ENV["DATABASE_USER_LOCAL"] %>
  host: <%= ENV["HOST_LOCAL"] %>

development:
  <<: *default
  database: blog_seo_app_development
test:
  <<: *default
  database: blog_seo_app_development_test

production:
  <<: *default
  database: blog_seo_app_development_production
  username: blog_seo_app_development
  password: <%= ENV["DATABASE_PASSWORD"] %>
